export const sectors=[
    { index: 0, value: "Prize 1" },
    { index: 1, value: "Prize 2" },
    { index: 2, value: "Prize 3" },
    { index: 3, value: "Prize 4" },
    { index: 4, value: "Prize 5" },
    { index: 5, value: "Prize 6" },
    { index: 0, value: "Prize 7" },
    { index: 1, value: "Prize 8" },
    { index: 2, value: "Prize 9" },
    { index: 3, value: "Prize 10" },
    { index: 4, value: "Prize 11" },
    { index: 5, value: "Prize 12" },
    { index: 0, value: "Prize 13" },
    { index: 1, value: "Prize 14" },
    { index: 2, value: "Prize 15" },
    { index: 3, value: "Prize 16" },
    { index: 4, value: "Prize 17" },
    { index: 5, value: "Prize 18" },
  ];